version: '3'
services:
  rss_parser:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - NATURE_RSS_URL=https://www.nature.com/nature.rss
      - BIORXIV_RSS_URL=http://connect.biorxiv.org/biorxiv_xml.php?subject=all
    restart: unless-stopped